export default function Footer() {
  return (
    <footer className="bg-gray-50 border-t border-gray-200 mt-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Brand */}
          <div>
            <p className="font-bold text-[#1a56db] text-lg mb-2">Midwest Civic Tools</p>
            <p className="text-sm text-gray-600">
              Free civic calculators and explainers for residents and small businesses.
            </p>
            <p className="text-xs text-gray-500 mt-2">
              Not affiliated with any government agency.
            </p>
          </div>

          {/* Data Sources */}
          <div>
            <p className="font-semibold text-gray-700 text-sm mb-3">Data Sources</p>
            <p className="text-xs text-gray-500 leading-relaxed">
              Data sourced from USDA/FNS, Indiana FSSA, Indiana DOE, Michigan LEO, Illinois DOL, Ohio BWC, and U.S. DOL.
              Benefit amounts and income thresholds are based on publicly available 2026 information as of publication.
              Always verify with the relevant state or federal agency for official eligibility determinations.
            </p>
          </div>
        </div>

        {/* Disclaimer block */}
        <div className="mt-8 bg-yellow-50 border border-yellow-200 rounded-xl p-5 text-xs text-gray-600 leading-relaxed space-y-2">
          <p className="font-semibold text-gray-800 text-sm">Important Disclaimers — Please Read</p>
          <p>
            <strong>Not legal or financial advice.</strong> The information on this site is provided for general
            informational and educational purposes only. Nothing on this site constitutes legal advice, financial
            advice, tax advice, or professional guidance of any kind. Do not rely on this site as a substitute for
            advice from a licensed attorney, financial advisor, or government caseworker.
          </p>
          <p>
            <strong>AI-generated content.</strong> The data, calculations, and text on this site were compiled with
            the assistance of AI tools. While we have made reasonable efforts to
            verify accuracy against primary government sources, AI-generated content can contain errors, omissions,
            or outdated information. Use at your own risk.
          </p>
          <p>
            <strong>Data may change.</strong> Government benefit rules, income thresholds, wage rates, and program
            eligibility requirements change frequently — sometimes with little public notice. The information on this
            site reflects our best understanding of the rules as of the date of publication and may not reflect
            recent changes. Always verify current rules directly with the relevant agency before making any decisions.
          </p>
          <p>
            <strong>No guarantees.</strong> We make no representations or warranties of any kind, express or implied,
            about the completeness, accuracy, reliability, or suitability of any information on this site. Any
            reliance you place on this information is strictly at your own risk.
          </p>
          <p>
            <strong>No government affiliation.</strong> This site is an independent, privately operated project. It
            is not affiliated with, endorsed by, or operated by the State of Indiana, FSSA, USDA, Indiana DOE, or any
            other government agency.
          </p>
          <p>
            <strong>SNAP and benefit eligibility.</strong> SNAP eligibility decisions are made solely by your local
            FSSA office. Item-level eligibility under Indiana&apos;s Smart SNAP waiver may vary by retailer POS
            configuration, product labeling, and regulatory updates. When in doubt, verify with your caseworker or
            the Indiana FSSA at{' '}
            <a href="https://www.in.gov/fssa/dfr/" className="underline text-[#1a56db] hover:text-blue-700" target="_blank" rel="noopener noreferrer">
              in.gov/fssa/dfr
            </a>.
          </p>
          <p>
            <strong>Data Rights letters.</strong> Letters generated by the Data Rights tool are templates only.
            They are not legal documents and have not been reviewed by an attorney. Sending a letter does not
            guarantee a company will respond or comply. Consult a lawyer for complex data privacy matters.
          </p>
        </div>

        <div className="mt-6 pt-6 border-t border-gray-200 text-center text-xs text-gray-400">
          <p>© {new Date().getFullYear()} Midwest Civic Tools. MIT License. Open source.</p>
          <p className="mt-1">
            <a href="/disclaimer" className="underline hover:text-gray-600 transition-colors">Full Disclaimer</a>
          </p>
        </div>
      </div>
    </footer>
  );
}
